Shopping List rendering for user
the-collab-lab/tcl-68-smart-shopping-list pull request #19
Opened 2024-02-07 19:36 UTC by sdmisra

## Description

This enables a user to view the shared lists for their email as well as the list items of those shared lists. 

## Related Issue

closes #2 

## Acceptance Criteria

- [x] The `useShoppingLists` hook is used in `App.jsx` to get the shopping lists a user has access to from the database
- [x] The lists are passed into the `Home` component as a prop named `data`
- [x] The `setListPath` function is passed into the `Home` component so we can update the current list
- [x] The `useShoppingListData` hook is used in `App.jsx` to get the items in the current list from the Firestore database
- [x] The list is passed into the `List` component as a prop named `data`
- [x] In `Home.jsx`, the `SingleList` component is used to render the name of each shopping list a user is subscribed to
- [x] In `List.jsx`, the `ListItem` component is used to render the name of each item

## Type of Changes

`new feature`

## Updates

### Before
![Screenshot 2024-02-07 at 12 29 02 PM](https://github.com/the-collab-lab/tcl-68-smart-shopping-list/assets/117242156/c4983eef-7602-4679-b0de-b90e8c850cfe)
![Screenshot 2024-02-07 at 12 29 53 PM](https://github.com/the-collab-lab/tcl-68-smart-shopping-list/assets/117242156/dcdd3aec-5538-4622-be57-4447081eae93)

### After
![Screenshot 2024-02-07 at 12 30 13 PM](https://github.com/the-collab-lab/tcl-68-smart-shopping-list/assets/117242156/1c7b89a6-2586-47fb-8304-349dee3fb503)
![Screenshot 2024-02-07 at 12 30 49 PM](https://github.com/the-collab-lab/tcl-68-smart-shopping-list/assets/117242156/668cd11e-6a45-4ff3-afec-e25bfa4b2d9b)

## Testing Steps / QA Criteria

1. Review preview deployment that is based off this PR:
2. When on home page - sign in, review if 'dinner' list appears (shared list)
3. Click dinner to ensure local storage retrieves database info
4. navigate to [deployment address]/list
5. confirm that 'milk' and 'eggs' are visible within dinner list route

2024-02-08 22:23 UTC, andiedoescode reviewed
It all looks good!
Do you think the console logs in App.jsx (Ln 32, 33, 40) and firebase.js (Ln 33-35) will be helpful as we work with the API later on?

2024-02-09 04:36 UTC, DevinaG007 approved these changes
Aside from the commented lines Andrea mentioned, I think it looks good!

2024-02-09 17:36 UTC, sdmisra commented
> It all looks good! Do you think the console logs in App.jsx (Ln 32, 33, 40) and firebase.js (Ln 33-35) will be helpful as we work with the API later on?

I think they might be helpful, but we could always add them as we need to in the future if we wanted to remove them for this PR. They were great for troubleshooting our initial attempts at using the Firebase data.

2024-02-09 18:03 UTC, andiedoescode approved these changes
Looks good! :D

2024-02-10 15:07 UTC, cafloyd requested changes
Really nice job sticking with what turned out to be a tougher issue this week, @sdmisra and @etiry !! 

Just one request to remove the commented out console logs left over from debugging! I think they got left in the hubub of troubleshooting during office hours 😊

2024-02-10 15:07 UTC, cafloyd commented on src/App.jsx
> +	// console.log('email', userEmail)
I would echo Andrea and Devina's suggestion to remove these commented out console logs to clean up our files a bit!

```suggestion
```

2024-02-10 15:07 UTC, cafloyd commented on src/App.jsx
> +	// console.log('lists', lists);
```suggestion
```

2024-02-10 15:07 UTC, cafloyd commented on src/api/firebase.js
> +		// console.log('id', userId)
```suggestion
```

2024-02-10 15:24 UTC, sdmisra commented
Suggested changes from @andiedoescode, @DevinaG007, @cafloyd applied using the GitHub UI, I'll keep in mind that we don't want to leave in console logs in general when merging to main in the future

2024-02-10 18:20 UTC, cafloyd approved these changes
Looks great!! Thanks for cleaning things up, and really nice job troubleshooting those Firebase issues - I was really impressed to see your debugging process!

Congrats on completing your first issue, @sdmisra and @etiry !! You should be ok to merge this PR now!

<img src="https://media2.giphy.com/media/XreQmk7ETCak0/giphy.gif"/>

2024-02-11 12:12 UTC, merged