Et ap check item empty dupe
the-collab-lab/tcl-68-smart-shopping-list pull request #30
Opened 2024-03-06 21:43 UTC by etiry

## Description

Adds checks to user input of new items to alert the user if they submitted an empty item name or submitted an item that is already on their list after normalizing case and punctuation

## Related Issue

closes #10 

## Acceptance Criteria

- [x] Show an error message if the user tries to submit an empty item
- [x] Show an error message if the user tries to submit a new item that is _identical_ to an existing name. For instance, if the list contains `apples` and the user adds `apples`.
- [x] Show an error message if the user tries to submit a new item that matches an existing name with punctuation and casing normalized. For instance, if the list contains `apples` and the user adds `aPples` or `apples,` or `a pples`.
- [x] The user’s original input is saved in the database

## Type of Changes

`enhancement`

## Updates

### Before

### After

## Testing Steps / QA Criteria

- Sign in and select the dinner list
- Navigate to the Manage List view
- Try to submit the form without entering an item name
- Confirm that an alert displays saying "Please enter an item name"
- Try to add an item that is already on the list by entering it identically (e.g., Gruyere not gruyere)
- Confirm that an alert displays saying "This item already exists in the list"
- Try to add an item that is already on the list by changing the casing and/or adding punctuation or spaces (e.g., gruyere or Gruyere!)
- Confirm that an alert displays saying "This item already exists in the list"
- Try to add an item that is not on the list
- Confirm it gets added successfully
- Confirm it gets added as you typed it in rather than a normalized version (e.g., Oreos not oreos)

2024-03-08 17:42 UTC, sdmisra commented on src/views/ManageList.jsx
> +			.replace(/[!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~/\s]/g, '');
praise: regular expressions are really intimidating to write at times, they way you both implemented it here looks like it'll catch any symbols that users might try to put in their list that might cause problems, nice!

2024-03-08 17:43 UTC, sdmisra submitted a review, later dismissed
This looks good to me, nice work this week!

2024-03-09 17:03 UTC, raaynaldo requested changes

2024-03-09 17:03 UTC, raaynaldo commented on src/views/ManageList.jsx
> +		}
refactor: we could move the second if clause to be early, so we don't need to have nested if for the first if clause

```suggestion
		if (!newItem.itemName) {
			alert('Please enter an item name');
			return;
		}

		//edge case: what if someone decides to put only puncutation as item name
		const itemName = newItem.itemName
			.toLowerCase()
			.replace(/[!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~/\s]/g, '');
		console.log('itemName:', itemName);

		if (currentList.includes(itemName)) {
			alert('This item already exists in the list.');
			return;
		}
```

2024-03-09 17:03 UTC, raaynaldo commented
Great job on utilizing regex

2024-03-09 17:57 UTC, DevinaG007 submitted a review, later dismissed
Praise: Nice comparison choice used on line 36 of ```ManageList```. I tested "New England Clam Chowder" versus "Clam Chowder" and it worked! 

![success](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNnYzd29zemN4c3Z0aXNoOXd3bGpmdXhrZXhvYmhzZjl1Mm82azJ0dyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/skmziDEEjiin6/giphy.gif)

2024-03-10 00:56 UTC, raaynaldo approved these changes
Thanks!

2024-03-10 01:02 UTC, merged